use crate::grammar::model::{Cardinality, Element, Model};
use crate::scala_gen::config::ScalaAstGenConfig;
use heck::ToLowerCamelCase;
use std::collections::HashMap;
use std::fmt::Error;
use std::fmt::Write;

pub fn generate_scala(model: &Model, config: &ScalaAstGenConfig) -> Result<String, Error> {
    let mut out = String::new();

    // Sorted for deterministic output.
    let tokens = sorted(model.tokens.iter().cloned().collect());
    let trait_nodes = sorted(config.trait_nodes.clone());
    let non_trait_nodes = sorted(
        model
            .node_names
            .iter()
            .filter(|name| !trait_nodes.contains(*name))
            .cloned()
            .collect(),
    );

    let trait_membership = trait_membership_relation(model, &trait_nodes);
    let inverse_trait_membership =
        inverse_trait_membership_relation(&non_trait_nodes, &trait_nodes, &trait_membership);

    emit_header(&mut out, config)?;
    emit_imports(&mut out)?;
    emit_object_open(&mut out, config)?;
    emit_factory_method(&mut out, config)?;
    emit_kind_map(&mut out, config, &non_trait_nodes, &tokens)?;
    emit_base_node_and_token_traits(&mut out, config)?;
    emit_trait_kind_sets(&mut out, config, &trait_nodes, &trait_membership)?;
    emit_trait_declarations(&mut out, config, &trait_nodes)?;
    emit_node_case_classes(
        &mut out,
        model,
        config,
        &non_trait_nodes,
        &inverse_trait_membership,
    )?;
    emit_token_case_classes(&mut out, config, &tokens)?;
    emit_object_close(&mut out)?;

    Ok(out)
}

/// Builds a map `TraitNode -> [NonTraitNode, ...]` denoting which non-trait nodes
/// belong to a given trait.
fn trait_membership_relation(
    model: &Model,
    trait_nodes: &[String],
) -> HashMap<String, Vec<String>> {
    let mut result = HashMap::new();

    for trait_node in trait_nodes {
        let mut members = model
            .collect_descendant_nodes(trait_node, &|name| trait_nodes.contains(&name.to_string()))
            .into_iter()
            .collect::<Vec<_>>();

        members.sort();
        result.insert(trait_node.clone(), members);
    }

    result
}

/// The inverse of `trait_membership_relation`, i.e. a map
/// `NonTraitNode -> [TraitNode, ...]`, which we use to tell which
/// traits a case class extends.
fn inverse_trait_membership_relation(
    non_trait_nodes: &[String],
    trait_nodes: &[String],
    trait_membership: &HashMap<String, Vec<String>>,
) -> HashMap<String, Vec<String>> {
    let mut result = HashMap::new();

    // TODO: there's probably a better way of writing this...

    for node in non_trait_nodes {
        let mut traits_for_node = Vec::new();

        for trait_node in trait_nodes {
            let Some(members) = trait_membership.get(trait_node) else {
                continue;
            };

            if members.contains(node) {
                traits_for_node.push(trait_node.clone());
            }
        }

        result.insert(node.clone(), traits_for_node);
    }

    result
}

fn emit_header(out: &mut String, config: &ScalaAstGenConfig) -> Result<(), Error> {
    write!(
        out,
        concat!(
            "package {}\n\n",
            "// Automatically generated by rust_ast_gen v{}\n",
            "// Do not edit directly!\n"
        ),
        config.package_name, config.codegen_version
    )?;

    if let Some(codegen_date) = &config.codegen_date {
        writeln!(out, "// Generated on {codegen_date}")?;
    }

    write!(out, "\n")
}

// TODO: Should come from the config
fn emit_imports(out: &mut String) -> Result<(), Error> {
    write!(out, "import ujson.Value\n")
}

fn emit_object_open(out: &mut String, config: &ScalaAstGenConfig) -> Result<(), Error> {
    write!(out, "object {} {{\n", config.object_name)
}

fn emit_object_close(out: &mut String) -> Result<(), Error> {
    write!(out, "\n}}")
}

fn emit_factory_method(out: &mut String, config: &ScalaAstGenConfig) -> Result<(), Error> {
    write!(
        out,
        concat!(
            "\n",
            "  def create{base}(json: Value): {base} = {{\n",
            "    val kind = json(\"nodeKind\").str\n",
            "    _kindMap.getOrElse(\n",
            "      kind,\n",
            "      throw new UnsupportedOperationException(s\"Kind '$kind' is not a known Rust node or token kind\")\n",
            "    )(json)\n",
            "  }}\n"
        ),
        base = config.base_node_trait
    )
}

fn emit_kind_map(
    out: &mut String,
    config: &ScalaAstGenConfig,
    concrete_nodes: &[String],
    tokens: &[String],
) -> Result<(), Error> {
    write!(
        out,
        "\n  private val _kindMap: Map[String, Value => {}] = Map(\n",
        config.base_node_trait
    )?;

    for node in concrete_nodes {
        let json_kind = (config.node_name_to_json_kind)(node);
        let scala_name = (config.node_name_to_scala_name)(node);
        writeln!(out, "    \"{json_kind}\" -> (json => {scala_name}(json)),")?;
    }

    for token in tokens {
        let json_kind = (config.token_name_to_json_kind)(token);
        let scala_name = (config.token_name_to_scala_name)(token);
        writeln!(out, "    \"{json_kind}\" -> (json => {scala_name}(json)),")?;
    }

    write!(out, "  )\n")
}

fn emit_base_node_and_token_traits(
    out: &mut String,
    config: &ScalaAstGenConfig,
) -> Result<(), Error> {
    write!(
        out,
        concat!(
            "\n",
            "  sealed trait {node_base} {{\n",
            "    def json: Value\n",
            "    protected lazy val _children: Seq[Value] = json.obj.get(\"children\").map(_.arr.toSeq).getOrElse(Seq.empty)\n",
            "    protected lazy val _childrenByKind: Map[String, Seq[Value]] = _children.groupBy(_(\"nodeKind\").str)\n",
            "    private lazy val rangeObj = json.obj.get(\"range\").map(_.obj)\n",
            "    private def rangeField(name: String): Option[Int] = rangeObj.flatMap(_.get(name)).map(_.num.toInt)\n",
            "    def startOffset: Option[Int] = rangeField(\"startOffset\")\n",
            "    def endOffset: Option[Int] = rangeField(\"endOffset\")\n",
            "    def startLine: Option[Int] = rangeField(\"startLine\")\n",
            "    def startColumn: Option[Int] = rangeField(\"startColumn\")\n",
            "  }}\n",
            "\n",
            "  sealed trait {token_base} extends {node_base}\n"
        ),
        node_base = config.base_node_trait,
        token_base = config.base_token_trait
    )
}

fn emit_trait_kind_sets(
    out: &mut String,
    config: &ScalaAstGenConfig,
    trait_nodes: &[String],
    trait_descendants: &HashMap<String, Vec<String>>,
) -> Result<(), Error> {
    for trait_node in trait_nodes {
        let set_name = format!(
            "_{}Kinds",
            (config.node_name_to_scala_name)(trait_node).to_lower_camel_case()
        );
        let kinds = trait_descendants
            .get(trait_node)
            .into_iter()
            .flatten()
            .map(|node| (config.node_name_to_json_kind)(node))
            .collect::<Vec<_>>();

        writeln!(out, "\n  private val {set_name}: Set[String] = Set(")?;
        for kind in kinds {
            writeln!(out, "    \"{kind}\",")?;
        }
        write!(out, "  )\n")?;
    }

    Ok(())
}

fn emit_trait_declarations(
    out: &mut String,
    config: &ScalaAstGenConfig,
    trait_nodes: &[String],
) -> Result<(), Error> {
    for trait_node in trait_nodes {
        let scala_name = (config.node_name_to_scala_name)(trait_node);
        writeln!(
            out,
            "\n  sealed trait {scala_name} extends {}",
            config.base_node_trait
        )?;
    }

    Ok(())
}

fn emit_node_case_classes(
    out: &mut String,
    model: &Model,
    config: &ScalaAstGenConfig,
    non_trait_nodes: &[String],
    inverse_trait_membership: &HashMap<String, Vec<String>>,
) -> Result<(), Error> {
    for node in non_trait_nodes {
        let scala_name = (config.node_name_to_scala_name)(node);
        let extends = std::iter::once(config.base_node_trait.clone())
            .chain(
                inverse_trait_membership
                    .get(node)
                    .into_iter()
                    .flatten()
                    .map(|trait_node| (config.node_name_to_scala_name)(trait_node)),
            )
            .collect::<Vec<_>>()
            .join(" with ");

        writeln!(
            out,
            "\n  final case class {scala_name}(json: Value) extends {extends} {{"
        )?;

        if let Some(elements) = model.node_elements.get(node) {
            for element in elements {
                emit_accessor(out, model, config, element)?;
            }
        }

        write!(out, "  }}\n")?;
    }

    Ok(())
}

fn emit_accessor(
    out: &mut String,
    model: &Model,
    config: &ScalaAstGenConfig,
    element: &Element,
) -> Result<(), Error> {
    let accessor = scala_safe_identifier(&scala_accessor_name(element, model, config));
    let scala_type = scala_type_name(element, model, config);
    let rhs = scala_json_lookup_code(element, model, config);

    match element.cardinality {
        Cardinality::One => writeln!(out, "    def {accessor}: {scala_type} = {rhs}",),
        Cardinality::Optional => writeln!(out, "    def {accessor}: Option[{scala_type}] = {rhs}",),
        Cardinality::Many => writeln!(out, "    def {accessor}: Seq[{scala_type}] = {rhs}",),
    }
}

fn emit_token_case_classes(
    out: &mut String,
    config: &ScalaAstGenConfig,
    tokens: &[String],
) -> Result<(), Error> {
    for token in tokens {
        let scala_name = (config.token_name_to_scala_name)(token);
        writeln!(
            out,
            "\n  final case class {scala_name}(json: Value) extends {}",
            config.base_token_trait
        )?;
    }

    Ok(())
}

fn scala_accessor_name(element: &Element, model: &Model, config: &ScalaAstGenConfig) -> String {
    if model.tokens.contains(&element.node_or_token_name) {
        (config.token_name_to_scala_name)(&element.node_or_token_name).to_lower_camel_case()
    } else {
        element.node_or_token_name.to_lower_camel_case()
    }
}

fn scala_type_name(element: &Element, model: &Model, config: &ScalaAstGenConfig) -> String {
    if model.tokens.contains(&element.node_or_token_name) {
        (config.token_name_to_scala_name)(&element.node_or_token_name)
    } else {
        (config.node_name_to_scala_name)(&element.node_or_token_name)
    }
}

fn scala_json_lookup_code_for_token(element: &Element, config: &ScalaAstGenConfig) -> String {
    let create_fn = format!("create{}", config.base_node_trait);
    let kind = (config.token_name_to_json_kind)(&element.node_or_token_name);
    let scala_type = (config.token_name_to_scala_name)(&element.node_or_token_name);
    match element.cardinality {
        Cardinality::One => {
            format!("{create_fn}(_childrenByKind(\"{kind}\").head).asInstanceOf[{scala_type}]")
        }
        Cardinality::Optional => format!(
            "_childrenByKind.get(\"{kind}\").flatMap(_.headOption).map({create_fn}(_).asInstanceOf[{scala_type}])"
        ),
        Cardinality::Many => format!(
            "_childrenByKind.getOrElse(\"{kind}\", Seq.empty).map({create_fn}(_).asInstanceOf[{scala_type}])"
        ),
    }
}

fn scala_json_lookup_code_for_trait_node(element: &Element, config: &ScalaAstGenConfig) -> String {
    let create_fn = format!("create{}", config.base_node_trait);
    let kinds_name = format!(
        "_{}Kinds",
        (config.node_name_to_scala_name)(&element.node_or_token_name).to_lower_camel_case()
    );
    let scala_type = (config.node_name_to_scala_name)(&element.node_or_token_name);
    match element.cardinality {
        Cardinality::One => format!(
            "{create_fn}(_children.find(child => {kinds_name}.contains(child(\"nodeKind\").str)).get).asInstanceOf[{scala_type}]"
        ),
        Cardinality::Optional => format!(
            "_children.find(child => {kinds_name}.contains(child(\"nodeKind\").str)).map({create_fn}(_).asInstanceOf[{scala_type}])"
        ),
        Cardinality::Many => format!(
            "_children.filter(child => {kinds_name}.contains(child(\"nodeKind\").str)).map({create_fn}(_).asInstanceOf[{scala_type}])"
        ),
    }
}

fn scala_json_lookup_code_for_non_trait_node(
    element: &Element,
    config: &ScalaAstGenConfig,
) -> String {
    let create_fn = format!("create{}", config.base_node_trait);
    let kind = (config.node_name_to_json_kind)(&element.node_or_token_name);
    let scala_type = (config.node_name_to_scala_name)(&element.node_or_token_name);

    match element.cardinality {
        Cardinality::One => {
            format!("{create_fn}(_childrenByKind(\"{kind}\").head).asInstanceOf[{scala_type}]")
        }
        Cardinality::Optional => format!(
            "_childrenByKind.get(\"{kind}\").flatMap(_.headOption).map({create_fn}(_).asInstanceOf[{scala_type}])"
        ),
        Cardinality::Many => format!(
            "_childrenByKind.getOrElse(\"{kind}\", Seq.empty).map({create_fn}(_).asInstanceOf[{scala_type}])"
        ),
    }
}

fn scala_json_lookup_code(element: &Element, model: &Model, config: &ScalaAstGenConfig) -> String {
    if model.tokens.contains(&element.node_or_token_name) {
        scala_json_lookup_code_for_token(element, config)
    } else if config.trait_nodes.contains(&element.node_or_token_name) {
        scala_json_lookup_code_for_trait_node(element, config)
    } else {
        scala_json_lookup_code_for_non_trait_node(element, config)
    }
}

fn sorted(mut values: Vec<String>) -> Vec<String> {
    values.sort();
    values
}

fn scala_safe_identifier(name: &str) -> String {
    if !is_scala_keyword(name) {
        name.to_string()
    } else {
        format!("`{name}`")
    }
}

fn is_scala_keyword(name: &str) -> bool {
    matches!(
        name,
        "abstract"
            | "case"
            | "catch"
            | "class"
            | "def"
            | "do"
            | "else"
            | "enum"
            | "export"
            | "extends"
            | "false"
            | "final"
            | "finally"
            | "for"
            | "forSome"
            | "given"
            | "if"
            | "implicit"
            | "import"
            | "lazy"
            | "match"
            | "new"
            | "null"
            | "object"
            | "override"
            | "package"
            | "private"
            | "protected"
            | "return"
            | "sealed"
            | "super"
            | "then"
            | "this"
            | "throw"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "val"
            | "var"
            | "while"
            | "with"
            | "yield"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;
    use ungrammar::Grammar;

    fn example_config() -> ScalaAstGenConfig {
        ScalaAstGenConfig {
            package_name: "example".to_string(),
            object_name: "ExampleAst".to_string(),
            base_node_trait: "AstNode".to_string(),
            base_token_trait: "AstToken".to_string(),
            node_name_to_json_kind: |n| format!("{}_NODE", n.to_uppercase()),
            node_name_to_scala_name: |n| format!("{}Node", n),
            token_name_to_json_kind: |n| format!("{}_TOKEN", n.to_uppercase()),
            token_name_to_scala_name: |n| format!("{}Token", n),
            trait_nodes: vec![],
            codegen_version: "0.0.0".to_string(),
            codegen_date: Some("2020-01-01".to_string()),
        }
    }

    #[test]
    fn test_1_trait_1_node_1_token() {
        let grammar = Grammar::from_str(
            r"
            Expr = Literal?
            Literal = 'foo'",
        )
        .unwrap();

        let model = Model::from_ungrammar(&grammar).unwrap();
        let mut config = example_config();
        config.trait_nodes = vec!["Expr".to_string()];
        let scala = generate_scala(&model, &config).unwrap();

        assert_eq!(
            scala,
            r#"package example

// Automatically generated by rust_ast_gen v0.0.0
// Do not edit directly!
// Generated on 2020-01-01

import ujson.Value
object ExampleAst {

  def createAstNode(json: Value): AstNode = {
    val kind = json("nodeKind").str
    _kindMap.getOrElse(
      kind,
      throw new UnsupportedOperationException(s"Kind '$kind' is not a known Rust node or token kind")
    )(json)
  }

  private val _kindMap: Map[String, Value => AstNode] = Map(
    "LITERAL_NODE" -> (json => LiteralNode(json)),
    "FOO_TOKEN" -> (json => fooToken(json)),
  )

  sealed trait AstNode {
    def json: Value
    protected lazy val _children: Seq[Value] = json.obj.get("children").map(_.arr.toSeq).getOrElse(Seq.empty)
    protected lazy val _childrenByKind: Map[String, Seq[Value]] = _children.groupBy(_("nodeKind").str)
    private lazy val rangeObj = json.obj.get("range").map(_.obj)
    private def rangeField(name: String): Option[Int] = rangeObj.flatMap(_.get(name)).map(_.num.toInt)
    def startOffset: Option[Int] = rangeField("startOffset")
    def endOffset: Option[Int] = rangeField("endOffset")
    def startLine: Option[Int] = rangeField("startLine")
    def startColumn: Option[Int] = rangeField("startColumn")
  }

  sealed trait AstToken extends AstNode

  private val _exprNodeKinds: Set[String] = Set(
    "LITERAL_NODE",
  )

  sealed trait ExprNode extends AstNode

  final case class LiteralNode(json: Value) extends AstNode with ExprNode {
    def fooToken: fooToken = createAstNode(_childrenByKind("FOO_TOKEN").head).asInstanceOf[fooToken]
  }

  final case class fooToken(json: Value) extends AstToken

}"#
        );
    }

    #[test]
    fn test_nested_trait_membership_and_trait_accessors() {
        let grammar = Grammar::from_str(
            r"
            Stmt = Expr | Item | Let
            Expr = Literal | Call
            Item = Fn
            Let = 'let'
            Literal = 'lit'
            Call = 'call' Expr?
            Fn = 'fn' Name*
            Name = 'name'",
        )
        .unwrap();

        let model = Model::from_ungrammar(&grammar).unwrap();
        let mut config = example_config();
        config.trait_nodes = vec!["Stmt".to_string(), "Expr".to_string(), "Item".to_string()];
        let scala = generate_scala(&model, &config).unwrap();

        assert_eq!(
            scala,
            r#"package example

// Automatically generated by rust_ast_gen v0.0.0
// Do not edit directly!
// Generated on 2020-01-01

import ujson.Value
object ExampleAst {

  def createAstNode(json: Value): AstNode = {
    val kind = json("nodeKind").str
    _kindMap.getOrElse(
      kind,
      throw new UnsupportedOperationException(s"Kind '$kind' is not a known Rust node or token kind")
    )(json)
  }

  private val _kindMap: Map[String, Value => AstNode] = Map(
    "CALL_NODE" -> (json => CallNode(json)),
    "FN_NODE" -> (json => FnNode(json)),
    "LET_NODE" -> (json => LetNode(json)),
    "LITERAL_NODE" -> (json => LiteralNode(json)),
    "NAME_NODE" -> (json => NameNode(json)),
    "CALL_TOKEN" -> (json => callToken(json)),
    "FN_TOKEN" -> (json => fnToken(json)),
    "LET_TOKEN" -> (json => letToken(json)),
    "LIT_TOKEN" -> (json => litToken(json)),
    "NAME_TOKEN" -> (json => nameToken(json)),
  )

  sealed trait AstNode {
    def json: Value
    protected lazy val _children: Seq[Value] = json.obj.get("children").map(_.arr.toSeq).getOrElse(Seq.empty)
    protected lazy val _childrenByKind: Map[String, Seq[Value]] = _children.groupBy(_("nodeKind").str)
    private lazy val rangeObj = json.obj.get("range").map(_.obj)
    private def rangeField(name: String): Option[Int] = rangeObj.flatMap(_.get(name)).map(_.num.toInt)
    def startOffset: Option[Int] = rangeField("startOffset")
    def endOffset: Option[Int] = rangeField("endOffset")
    def startLine: Option[Int] = rangeField("startLine")
    def startColumn: Option[Int] = rangeField("startColumn")
  }

  sealed trait AstToken extends AstNode

  private val _exprNodeKinds: Set[String] = Set(
    "CALL_NODE",
    "LITERAL_NODE",
  )

  private val _itemNodeKinds: Set[String] = Set(
    "FN_NODE",
  )

  private val _stmtNodeKinds: Set[String] = Set(
    "CALL_NODE",
    "FN_NODE",
    "LET_NODE",
    "LITERAL_NODE",
  )

  sealed trait ExprNode extends AstNode

  sealed trait ItemNode extends AstNode

  sealed trait StmtNode extends AstNode

  final case class CallNode(json: Value) extends AstNode with ExprNode with StmtNode {
    def callToken: callToken = createAstNode(_childrenByKind("CALL_TOKEN").head).asInstanceOf[callToken]
    def expr: Option[ExprNode] = _children.find(child => _exprNodeKinds.contains(child("nodeKind").str)).map(createAstNode(_).asInstanceOf[ExprNode])
  }

  final case class FnNode(json: Value) extends AstNode with ItemNode with StmtNode {
    def fnToken: fnToken = createAstNode(_childrenByKind("FN_TOKEN").head).asInstanceOf[fnToken]
    def name: Seq[NameNode] = _childrenByKind.getOrElse("NAME_NODE", Seq.empty).map(createAstNode(_).asInstanceOf[NameNode])
  }

  final case class LetNode(json: Value) extends AstNode with StmtNode {
    def letToken: letToken = createAstNode(_childrenByKind("LET_TOKEN").head).asInstanceOf[letToken]
  }

  final case class LiteralNode(json: Value) extends AstNode with ExprNode with StmtNode {
    def litToken: litToken = createAstNode(_childrenByKind("LIT_TOKEN").head).asInstanceOf[litToken]
  }

  final case class NameNode(json: Value) extends AstNode {
    def nameToken: nameToken = createAstNode(_childrenByKind("NAME_TOKEN").head).asInstanceOf[nameToken]
  }

  final case class callToken(json: Value) extends AstToken

  final case class fnToken(json: Value) extends AstToken

  final case class letToken(json: Value) extends AstToken

  final case class litToken(json: Value) extends AstToken

  final case class nameToken(json: Value) extends AstToken

}"#
        );
    }

    #[test]
    fn test_date_omitted_from_header() {
        let grammar = Grammar::from_str("Expr = 'foo'").unwrap();

        let model = Model::from_ungrammar(&grammar).unwrap();
        let mut config = example_config();
        config.codegen_date = None;
        let scala = generate_scala(&model, &config).unwrap();

        assert!(scala.contains("// Automatically generated by rust_ast_gen v0.0.0"));
        assert!(scala.contains("// Do not edit directly!"));
        assert!(!scala.contains("// Generated on "));
    }

    #[test]
    fn test_reserved_scala_accessor_name() {
        let grammar = Grammar::from_str(
            r"
            Wrapper = Type
            Type = 'type'",
        )
        .unwrap();

        let model = Model::from_ungrammar(&grammar).unwrap();
        let config = example_config();
        let scala = generate_scala(&model, &config).unwrap();

        assert!(scala.contains("def `type`: TypeNode"));
    }
}
